version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf:ro
    #   - /var/log/nginx:/var/log/nginx
    restart: always
    environment:
      TZ: Asia/Tokyo
  certbot:
    image: certbot/dns-route53
    volumes:
      - ./aws-credentials:/root/.aws/config:ro
      - ./letsencrypt/lib:/var/lib/letsencrypt
      - ./letsencrypt/etc:/etc/letsencrypt
    command: certonly --dns-route53 --agree-tos -m amanekey@gmail.com -d *.turai.work -d turai.work
    environment:
      TZ: Asia/Tokyo
