version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf:ro
      - ./letsencrypt/etc:/etc/letsencrypt:ro
    restart: always
    environment:
      TZ: Asia/Tokyo
  certbot:
    image: certbot/dns-route53
    volumes:
      - ./aws-credentials:/root/.aws/config:ro
      - ./letsencrypt/lib:/var/lib/letsencrypt
      - ./letsencrypt/etc:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --dns-route53 --non-interactive; sleep 12h & wait $${!}; done;'"
    # 取得時
    # command: certonly --dns-route53 --agree-tos -m xxx@gmail.com -d *.turai.work -d turai.work --non-interactive
    restart: always
    environment:
      TZ: Asia/Tokyo
