name: Deploy docker-compose

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/thr3a/docker-compose
            docker compose pull
            docker compose build
            docker compose down
            docker compose up
