name: Deploy docker-compose

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al
      - name: Checkout repository
        uses: actions/checkout@v3
